---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
```


```{r}
datos <- read.csv("./CaracteristicasHogar.csv", sep="\t", header=T)
```

```{r}
filtrado <- datos %>% select(c(DIRECTORIO, ORDEN, P6020, P6034, P6051, P5502, P756S1, 
                               P6081, P6087, P6083, P6088, P1895, P1896, P8587))

filtrado <- filtrado %>% rename(
  Sexo = P6020,
  Fecha_nacimiento = P6034,
  Parentesco = P6051,
  Estado_civil = P5502, 
  Depertamento = P756S1,
  Padre_esta_vivo = P6081,
  Escolaridad_padre = P6087,
  Madre_esta_viva = P6083,
  Escolaridad_madre = P6088,
  Grado_satisfaccion_de_vida = P1895, 
  Grado_satisfaccion_ingresos = P1896,
  Nivel_educativo = P8587
)
```

```{r}
directorios <- filtrado %>% distinct(DIRECTORIO)
```

```{r}
nivelEducativoPareja <- filtrado %>% 
                        filter(Parentesco == 2) %>% 
                        select(DIRECTORIO, Nivel_educativo, Grado_satisfaccion_de_vida,
                               Escolaridad_padre, Escolaridad_madre) %>%
                        rename(Nivel_educativo_pareja = Nivel_educativo, 
                               Grado_satisfaccion_de_vida_pareja = Grado_satisfaccion_de_vida,
                               Escolaridad_padre_pareja = Escolaridad_padre,
                               Escolaridad_madre_pareja = Escolaridad_madre)
nivelEducativoPareja
```



```{r}
datos %>%
  filter(P6051 == 3) %>%
  group_by(DIRECTORIO) %>%
  summarise(n())
```

```{r}
nivelEducativo <- filtrado %>% 
                  filter(Parentesco == 1) %>% 
                  select(DIRECTORIO, Nivel_educativo, Estado_civil, Grado_satisfaccion_de_vida, 
                         Escolaridad_padre, Escolaridad_madre) %>%
                  rename(Nivel_educativo_jefe = Nivel_educativo,
                         Estado_civil_jefe = Estado_civil,
                         Grado_satisfaccion_de_vida_jefe = Grado_satisfaccion_de_vida,
                         Escolaridad_padre_jefe = Escolaridad_padre, 
                         Escolaridad_madre_jefe = Escolaridad_madre)
nivelEducativo
```

```{r}
numeroHijos <- filtrado %>% filter(Parentesco == 3) %>% group_by(DIRECTORIO) %>% summarise(Hijos=n())
numeroHijos
```

```{r}
numeroDePersonasPorCasa <-  filtrado %>% group_by(DIRECTORIO) %>% summarise(Numero_personas_por_casa=n())
numeroDePersonasPorCasa
```


```{r}
entradas <-  directorios %>% 
  inner_join(nivelEducativoPareja, by="DIRECTORIO") %>% 
  inner_join(nivelEducativo, by="DIRECTORIO") %>%
  inner_join(numeroHijos, by="DIRECTORIO") %>%
  inner_join(numeroDePersonasPorCasa, by="DIRECTORIO")
```





```{r}
entradas <- entradas %>% mutate(Nivel_educativo_pareja = as.factor(Nivel_educativo_pareja))%>% 
  mutate(Nivel_educativo_pareja = fct_recode(Nivel_educativo_pareja,
      "Ninguno" = "1",
      "Preescolar" = "2",
      "Basica Primaria (1 - 5)" = "3",
      "Basica secundaria (6 - 9)" = "4",
      "Media (10 - 13)" = "5",
      "Tecnico sin titulo" = "6",
      "Tecnico con titulo" = "7",
      "Tecnologico sin titulo" = "8",
      "Tecnologico con titulo" = "9",
      "Universitario sin titulo" = "10",
      "Universitario con titulo" = "11",
      "Postgrado sin titulo" = "12",
      "Postgrado con titulo" = "13"
  )
)
```

```{r}
entradas <- entradas %>% mutate(Nivel_educativo_jefe = as.factor(Nivel_educativo_jefe))%>% 
  mutate(Nivel_educativo_jefe = fct_recode(Nivel_educativo_jefe,
      "Ninguno" = "1",
      "Preescolar" = "2",
      "Basica Primaria (1 - 5)" = "3",
      "Basica secundaria (6 - 9)" = "4",
      "Media (10 - 13)" = "5",
      "Tecnico sin titulo" = "6",
      "Tecnico con titulo" = "7",
      "Tecnologico sin titulo" = "8",
      "Tecnologico con titulo" = "9",
      "Universitario sin titulo" = "10",
      "Universitario con titulo" = "11",
      "Postgrado sin titulo" = "12",
      "Postgrado con titulo" = "13"
  )
)
```
```{r}
entradas <- entradas %>% mutate(Escolaridad_madre_jefe = as.factor(Escolaridad_madre_jefe))%>% 
  mutate(Escolaridad_madre_jefe = fct_recode(Escolaridad_madre_jefe,
      "Algunos anios de primaria" = "1",
      "Toda la primaria" = "2",
      "Algunos anios de secundaria" = "3",
      "Toda la secundaria" = "4",
      "Uno o mas anios de tecnica o tecnologica" = "5",
      "Tecnica o tecnologica completa" = "6",
      "Uno o mas anios de universidad" = "7",
      "Universitaria completa" = "8",
      "Ninguno" = "9",
      "No sabe" = "10",
  )
)
```

```{r}
entradas <- entradas %>% mutate(Escolaridad_padre_jefe = as.factor(Escolaridad_padre_jefe))%>% 
  mutate(Escolaridad_padre_jefe = fct_recode(Escolaridad_padre_jefe,
      "Algunos anios de primaria" = "1",
      "Toda la primaria" = "2",
      "Algunos anios de secundaria" = "3",
      "Toda la secundaria" = "4",
      "Uno o mas anios de tecnica o tecnologica" = "5",
      "Tecnica o tecnologica completa" = "6",
      "Uno o mas anios de universidad" = "7",
      "Universitaria completa" = "8",
      "Ninguno" = "9",
      "No sabe" = "10",
  )
)
```

```{r}
entradas <- entradas %>% mutate(Escolaridad_padre_pareja = as.factor(Escolaridad_padre_pareja))%>% 
  mutate(Escolaridad_padre_pareja = fct_recode(Escolaridad_padre_pareja,
      "Algunos anios de primaria" = "1",
      "Toda la primaria" = "2",
      "Algunos anios de secundaria" = "3",
      "Toda la secundaria" = "4",
      "Uno o mas anios de tecnica o tecnologica" = "5",
      "Tecnica o tecnologica completa" = "6",
      "Uno o mas anios de universidad" = "7",
      "Universitaria completa" = "8",
      "Ninguno" = "9",
      "No sabe" = "10",
  )
)
```

```{r}
entradas <- entradas %>% mutate(Escolaridad_madre_pareja = as.factor(Escolaridad_madre_pareja))%>% 
  mutate(Escolaridad_madre_pareja = fct_recode(Escolaridad_madre_pareja,
      "Algunos anios de primaria" = "1",
      "Toda la primaria" = "2",
      "Algunos anios de secundaria" = "3",
      "Toda la secundaria" = "4",
      "Uno o mas anios de tecnica o tecnologica" = "5",
      "Tecnica o tecnologica completa" = "6",
      "Uno o mas anios de universidad" = "7",
      "Universitaria completa" = "8",
      "Ninguno" = "9",
      "No sabe" = "10",
  )
)
```

```{r}
entradas <- entradas %>% mutate(Estado_civil_jefe = as.factor(Estado_civil_jefe))%>% 
  mutate(Estado_civil_jefe = fct_recode(Estado_civil_jefe,
      "No esta casado(a) y vive en pareja hace menos de dos anios" = "1",
      "No esta casado(a) y vive en pareja hace dos anios o mas" = "2",
      "Esta viudo(a)" = "3",
      "Esta separado(a) o divorciado(a)" = "4",
      "Esta soltero(a)" = "5",
      "Esta casado(a)" = "6",
  )
)
```

```{r}
write.csv(entradas,"VariablesEntrada.csv")
```


