---
title: "modelo TAE"
author: "Laura Daniela Hoyos Pe침a"
date: "29/3/2021"
output: html_document
---


```{r}
library(psych)
library(caret)
library(tidyverse)
library(class)
```

```{r}
datos<-read.csv("VariablesEntrada.csv",header = TRUE,sep = ",")#39602 observaciones
datos<-na.omit(datos, na.action="omit")#19323 observaciones
```

###MODELOS

##KNN




```{r}
datos %>% 
  select(c('Nivel_educativo_jefe','Estado_civil_jefe','Grado_satisfaccion_de_vida_jefe','Hijos'))%>%
  head()
```

```{r}
datos_sel <- datos %>% 
  select(c('Nivel_educativo_jefe','Estado_civil_jefe','Grado_satisfaccion_de_vida_jefe','Hijos')) %>%
    mutate(Nivel_educativo_jefe = as.data.frame(dummy.code(Nivel_educativo_jefe))) %>%
    mutate(Estado_civil_jefe = as.data.frame(dummy.code(Estado_civil_jefe)))  
```


```{r}
numero<-123456789
set.seed(numero)
subset<-sample((1:nrow(datos)), (nrow(datos)/2)+1)
#datos_sel <- subset(datos,select = #c('Nivel_educativo_jefe','Estado_civil_jefe','Grado_satisfaccion_de_vida_jefe','Hijos','Numero_personas_por_casa'))
Train<-datos_sel[subset,] #9662 datos Entrena
Test<-datos_sel[-subset,] #9661 datos Validaci칩n
Train1<-Train[,-4]
Test1<-Test[,-4]
y_Train<-Train$Hijos
y_Test<-Test$Hijos
```

```{r}
save.image(file = "PrediccionHijos/Variables.Rdata")
```

###KNN
##Selecci칩n del K 칩ptimo

```{r,warning=FALSE,message=FALSE}

cv10<-trainControl(method='cv',number = 10)
set.seed(123456789)
fit<-train(Hijos~Nivel_educativo_jefe+Grado_satisfaccion_de_vida_jefe+Estado_civil_jefe+Numero_personas_por_casa,
method = 'knn',
tuneGrid = expand.grid(k=1:20),
trControl = cv10,
metric = "RMSE",
data = datos)
fit
```

```{r}

```

#K=18
```{r}
mod_knn_train<-knn(train=Train1,test=Train1,cl=y_Train,k=18,prob = TRUE, use.all = TRUE)
mod_knn_test<-knn(train=Train1,test=Test1,cl=y_Train,k=18)
summary(mod_knn_test)
summary(mod_knn_train)
summary(as.factor(y_Train))
matriz_confusion<-confusionMatrix(mod_knn_train, as.factor(y_Train))
matriz_confusion$table
error_knn<-1-matriz_confusion$overall['Accuracy']
names(error_knn) <- 'Tasa de error'
error_knn #Tasa de error
```
```{r}
matriz_confusion
```






```{r}
summary(as.factor(datos$Hijos))
```


```{r}
table(mod_knn_train,y_Train )
```
```{r}
mean(mod_knn_train==y_Train)
```
```{r}
mean(mod_knn_test==y_Test)
```


```{r}
plot(y_Train, mod_knn_train)
```

```{r}
resultados <- knnreg(x=Train1,test=Train1,cl=y_Train,k=18)
```


```{r}
EntradasParaPredecir <- datos_sel[1,-4]
```


```{r}
mod_knn_train<-knn(train=Train1,test=EntradasParaPredecir,cl=y_Train,k=18,prob = TRUE, use.all = TRUE)
```

```{r}
summary(mod_knn_train)
as.vector(mod_knn_train)
```

```{r}
datos_originales <- datos %>% 
  select(c('Nivel_educativo_jefe','Estado_civil_jefe','Grado_satisfaccion_de_vida_jefe','Hijos'))

ejemplo <- datos %>% 
  select(c('Nivel_educativo_jefe','Estado_civil_jefe','Grado_satisfaccion_de_vida_jefe','Hijos'))%>%
  head(1)


print(datos_originales)
print(ejemplo)
test <- datos_originales %>% add_row(Nivel_educativo_jefe = as.factor("Basica Primaria (1 - 5)"),
                      Estado_civil_jefe = as.factor("Esta casado(a)"),
                      Grado_satisfaccion_de_vida_jefe= 1 ,
                      Hijos= 2 )
test <- test %>% tail(1)

print(ejemplo$Nivel_educativo_jefe)
print(test$Nivel_educativo_jefe)
print(test %>% tail(1))
print( )
```
```{r}
as.factor(c("Basica Primaria (1 - 5)"))
```

```{r}
test %>%
    mutate(Nivel_educativo_jefe = as.data.frame(dummy.code(Nivel_educativo_jefe))) %>%
    mutate(Estado_civil_jefe = as.data.frame(dummy.code(Estado_civil_jefe))) %>% tail()
```
```{r}
print(dim(test[-4]))
print(dim(Train1))
print(test)
```


```{r}
mod_knn_train<-knn(train=Train1,test=test[-4],cl=y_Train,k=18,prob = TRUE, use.all = TRUE)
as.vector(mod_knn_train)
```

```{r}

test <- datos_originales %>% 
  select(c('Nivel_educativo_jefe','Estado_civil_jefe','Grado_satisfaccion_de_vida_jefe','Hijos')) %>%
  add_row(Nivel_educativo_jefe = as.factor("Basica Primaria (1 - 5)"),
                      Estado_civil_jefe = as.factor("Esta viudo(a)"),
                      Grado_satisfaccion_de_vida_jefe= 8 ,
                      Hijos= 1 ) %>%
    mutate(Nivel_educativo_jefe = as.data.frame(dummy.code(Nivel_educativo_jefe))) %>%
    mutate(Estado_civil_jefe = as.data.frame(dummy.code(Estado_civil_jefe)))  %>%
      tail(1)
test
```

